name: Lint and Format Check
on:
  pull_request:
    branches: ['*']

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint:check
      - name: Format check
        run: npm run format:check
